package com.acadview.countrylisting;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    ListView simpleList;
    String cities;
    int i;
    String countryList[] = {"Afghanistan"
            ,"Albania"
            ,"Algeria"
            ,"Andorra"
            ,"Angola"
            ,"Anguilla"
            ,"Antigua & Barbuda"
            ,"Argentina"
            ,"Armenia"
            ,"Australia"
            ,"Austria"
            ,"Azerbaijan"
            ,"Bahamas"
            ,"Bahrain"
            ,"Bangladesh"
            ,"Barbados"
            ,"Belarus"
            ,"Belgium"
            ,"Belize"
            ,"Benin"
            ,"Bermuda"
            ,"Bhutan"
            ,"Bolivia"
            ,"Bosnia & Herzegovina"
            ,"Botswana"
            ,"Brazil"
            ,"Brunei Darussalam"
            ,"Bulgaria"
            ,"Burkina Faso"
            ,"Myanmar/Burma"
            ,"Burundi"
            ,"Cambodia"
            ,"Cameroon"
            ,"Canada"
            ,"Cape Verde"
            ,"Cayman Islands"
            ,"Central African Republic"
            ,"Chad"
            ,"Chile"
            ,"China"
            ,"Colombia"
            ,"Comoros"
            ,"Congo"
            ,"Costa Rica"
            ,"Croatia"
            ,"Cuba"
            ,"Cyprus"
            ,"Czech Republic"
            ,"Democratic Republic of the Congo"
            ,"Denmark"
            ,"Djibouti"
            ,"Dominica"
            ,"Dominican Republic"
            ,"Ecuador"
            ,"Egypt"
            ,"El Salvador"
            ,"Equatorial Guinea"
            ,"Eritrea"
            ,"Estonia"
            ,"Ethiopia"
            ,"Fiji"
            ,"Finland"
            ,"France"
            ,"French Guiana"
            ,"Gabon"
            ,"Gambia"
            ,"Georgia"
            ,"Germany"
            ,"Ghana"
            ,"Great Britain"
            ,"Greece"
            ,"Grenada"
            ,"Guadeloupe"
            ,"Guatemala"
            ,"Guinea"
            ,"Guinea-Bissau"
            ,"Guyana"
            ,"Haiti"
            ,"Honduras"
            ,"Hungary"
            ,"Iceland"
            ,"India"
            ,"Indonesia"
            ,"Iran"
            ,"Iraq"
            ,"Israel and the Occupied Territories"
            ,"Italy"
            ,"Ivory Coast (Cote d'Ivoire)"
            ,"Jamaica"
            ,"Japan"
           ,"Jordan"
           ,"Kazakhstan"
           ,"Kenya"
           ,"Kosovo"
            ,"Kuwait"
            ,"Kyrgyz Republic (Kyrgyzstan)"
            ,"Laos"
            ,"Latvia"
            ,"Lebanon"
            ,"Lesotho"
            ,"Liberia"
            ,"Libya"
            ,"Liechtenstein"
            ,"Lithuania"
            ,"Luxembourg"
            ,"Republic of Macedonia"
            ,"Madagascar"
            ,"Malawi"
            ,"Malaysia"
            ,"Maldives"
            ,"Mali"
            ,"Malta"
            ,"Martinique"
            ,"Mauritania"
            ,"Mauritius"
            ,"Mayotte"
            ,"Mexico"
            ,"Moldova"
            ,"Republic of Monaco"
            ,"Mongolia"
            ,"Montenegro"
            ,"Montserrat"
            ,"Morocco"
            ,"Mozambique"
            ,"Namibia"
            ,"Nepal"
            ,"Netherlands"
            ,"New Zealand"
            ,"Nicaragua"
            ,"Niger"
            ,"Nigeria"
            ,"Korea, Democratic Republic of (North Korea)"
            ,"Norway"
            ,"Oman"
            ,"Pacific Islands"
            ,"Pakistan"
            ,"Panama"
            ,"Papua New Guinea"
            ,"Paraguay"
            ,"Peru"
            ,"Philippines"
            ,"Poland"
            ,"Portugal"
            ,"Puerto Rico"
            ,"Qatar"
            ,"Reunion"
            ,"Romania"
            ,"Russian Federation"
            ,"Rwanda"
            ,"Saint Kitts and Nevis"
            ,"Saint Lucia"
            ,"Saint Vincent's & Grenadines"
            ,"Samoa"
            ,"Sao Tome and Principe"
            ,"Saudi Arabia"
            ,"Senegal"
            ,"Serbia"
            ,"Seychelles"
            ,"Sierra Leone"
            ,"Singapore"
            ,"Slovak Republic (Slovakia)"
            ,"Slovenia"
            ,"Solomon Islands"
            ,"Somalia"
            ,"South Africa"
            ,"Korea, Republic of (South Korea)"
            ,"South Sudan"
            ,"Spain"
            ,"Sri Lanka"
            ,"Sudan"
            ,"Suriname"
            ,"Swaziland"
            ,"Sweden"
            ,"Switzerland"
            ,"Syria"
            ,"Tajikistan"
            ,"Tanzania"
            ,"Thailand"
            ,"Timor Leste"
            ,"Togo"
            ,"Trinidad & Tobago"
            ,"Tunisia"
            ,"Turkey"
            ,"Turkmenistan"
            ,"Turks & Caicos Islands"
            ,"Uganda"
            ,"Ukraine"
            ,"United Arab Emirates"
            ,"United States of America (USA)"
            ,"Uruguay"
            ,"Uzbekistan"
            ,"Venezuela"
            ,"Vietnam"
            ,"Virgin Islands (UK)"
            ,"Virgin Islands (US)"
            ,"Yemen"
            ,"Zambia"
            ,"Zimbabwe"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        simpleList = (ListView)findViewById(R.id.ListView);
        ArrayAdapter<String> arrayAdapter = new ArrayAdapter<String>(getApplicationContext(),android.R.layout.simple_list_item_1,countryList);
        simpleList.setAdapter(arrayAdapter);

        simpleList.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view,
                                    int position, long l) {

                Intent intent = new Intent(MainActivity.this, SecActivity.class);
                Toast.makeText(MainActivity.this,"Country : "  + countryList[position], Toast.LENGTH_SHORT).show();

                intent.putExtra("Country", position);

                startActivity(intent);
            }
        });

    }
}
